### ISSUE TITLE
mysql database update ?

### ISSUE THREAD

**Issue by yarekc** [travispessetto/php-updater#4]
hi,
Looks great. 
I have a question : can your system automatically synch 2 mysql DBs ?

Since php projects mostly use mysql and when you update the project, it is very common to add some fields to DB, can this be done with your project ?

regards

**Comment by travispessetto** [comment]
This is not something the script will do by itself due to the fact that each project has a different configuration file and could have different database types.  However, the updater allows scripts to be ran.  So, you can add a script to change your database if needed.

```
files:
        add:
           - {local: "db/migration1.php", remote: "db/migration1.php"}
scripts:
        do:
            - {script: "db/migration1.php", delete: true}
```
